apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world
  labels:
    app: node-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
      - name: node-hello-world
        image: raniasaleh/node-hello-world
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: node-hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-world
spec:
  selector:
    app: node-hello-world
  ports:
  - protocol: "TCP"
    port: 80
    nodePort: 30002
  type: NodePort
---
